services:
  db:
    image: mysql:8.0
    container_name: my-money-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mymoney
      MYSQL_USER: mymoney
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-money-api
    working_dir: /app
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_URL: http://localhost:4002
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mymoney
      DB_USERNAME: mymoney
      DB_PASSWORD: secret
    ports:
      - "4002:80"
    volumes:
      - ./:/app
      - ./database:/app/database
      - ./storage:/app/storage

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-money-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8095:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 50M

volumes:
  db_data:
